#### The following three methods are central to dataframe workflows used throughout this course:

df.eval(): Does calculations.

df.query(): Finds rows.

df.groupby(): Builds groups of rows.

In [2]:
import pandas as pd

In [3]:
data = {'colors' : ['red', 'green', 'yellow', 'orange', 'blue'], 'base' : [15,30,8,12,22], 'height' : [18,10,5,12,13]}
df = pd.DataFrame(data)
df

   colors  base  height
0     red    15      18
1   green    30      10
2  yellow     8       5
3  orange    12      12
4    blue    22      13

In [4]:
# lets calculate area of triangles
df['area'] = df.eval('base*height *0.5')
df

   colors  base  height   area
0     red    15      18  135.0
1   green    30      10  150.0
2  yellow     8       5   20.0
3  orange    12      12   72.0
4    blue    22      13  143.0

House Price Dataset (Feature Engineering)

In [5]:
import pandas as pd

df1 = pd.DataFrame({
    'area': [1000, 1500, 2000],
    'bedrooms': [2, 3, 4],
    'price': [200000, 300000, 400000]
})
df1

   area  bedrooms   price
0  1000         2  200000
1  1500         3  300000
2  2000         4  400000

In [6]:
# create new ML feature
df1['price_per_sqft'] = df1.eval('price/area')
df1

   area  bedrooms   price  price_per_sqft
0  1000         2  200000           200.0
1  1500         3  300000           200.0
2  2000         4  400000           200.0

In [7]:
# Combine Features
# How crowded a house is
df1['room_density'] = df1.eval('bedrooms/area')
df1

   area  bedrooms   price  price_per_sqft  room_density
0  1000         2  200000           200.0         0.002
1  1500         3  300000           200.0         0.002
2  2000         4  400000           200.0         0.002

In [8]:
df3 = pd.DataFrame({'A': [10,20,30],
                    'B': [1,2,3]})
df3

    A  B
0  10  1
1  20  2
2  30  3

In [9]:
df3['sum'] = df3['A'] + df3['B']
df3['multiply'] = df3['A'] * df3['B']

In [10]:
df3

    A  B  sum  multiply
0  10  1   11        10
1  20  2   22        40
2  30  3   33        90

### DataFrame.query()

#### The query() method finds rows for a given condition. It's an efficient way to filter a dataframe and get the rows you want.

Your code has a concept mistake — .query() is used on a DataFrame, not on a single column (Series).

In [11]:
df4 = pd.DataFrame({'month' : ["January", "February", "March", "April","May", "June", "July", "August","September", "October", "November", "December"
], 'days' : [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31], 'leap_days':[0,1,0,0,0,0,0,0,0,0,0,0]})
df4

        month  days  leap_days
0     January    31          0
1    February    28          1
2       March    31          0
3       April    30          0
4         May    31          0
5        June    30          0
6        July    31          0
7      August    31          0
8   September    30          0
9     October    31          0
10   November    30          0
11   December    31          0

In [12]:
max = df4.query('days > 30')
max

# df4.query('days > 30') returns a filtered DataFrame

       month  days  leap_days
0    January    31          0
2      March    31          0
4        May    31          0
6       July    31          0
7     August    31          0
9    October    31          0
11  December    31          0

In [13]:
min = df4.query('days==days.min()')
min

      month  days  leap_days
1  February    28          1

In [15]:
data = {'days': ['Mon', 'Tue', 'Wed','Thu','Fri','Sat','Sun'],'temp':[22,25,20,23,28,25,23]}
df4 = pd.DataFrame(data)
df4

  days  temp
0  Mon    22
1  Tue    25
2  Wed    20
3  Thu    23
4  Fri    28
5  Sat    25
6  Sun    23

In [22]:
df4.query('temp>24')
df4.query('temp <= 22')
df4.query('temp == 23')
df4.query('temp! = 25')

  days  temp
0  Mon    22
2  Wed    20
3  Thu    23
4  Fri    28
6  Sun    23

In [24]:
df5 = pd.DataFrame({'name':['ana','bob','cat','dan'],'time':[30,45,25,35]})
df5

  name  time
0  ana    30
1  bob    45
2  cat    25
3  dan    35

In [ ]:
df5.query('name == "cat"')
# df5.query('name in ["cat","bob"]')
df5[df5["name"].isin(["cat", "bob"])]

  name  time
1  bob    45
2  cat    25

In [35]:
df5.query('name >= "c"')

  name  time
2  cat    25
3  dan    35

In [37]:
df6 = pd.DataFrame()
df6['color'] = ['red', 'blue', 'green', 'yellow']
df6['votes'] = [20,35,25,25]
df6

    color  votes
0     red     20
1    blue     35
2   green     25
3  yellow     25

In [40]:
df6.query('votes == 30 or votes == 35')
df6.query('votes in [15,20,30]')

  color  votes
0   red     20

In [41]:


sd = pd.DataFrame({
    "name": ["Ali", "Sara", "John", "Ayesha", "Bob"],
    "salary": [50000, 80000, 120000, 70000, 40000],
    "department": ["IT", "HR", "IT", "Finance", "HR"]
})

sd

     name  salary department
0     Ali   50000         IT
1    Sara   80000         HR
2    John  120000         IT
3  Ayesha   70000    Finance
4     Bob   40000         HR

In [ ]:
# Get employees from IT AND salary greter than 60,000
sd.query('department == "IT" and salary > 50000')
# Get employees from IT department
sd.query('department == "IT"')
# Get employees with salary between 50,000 and 100,000
sd.query(' 50000 < salary < 100000 ')
# Get employees whose name is either "Ali" or "Sara"
sd.query( 'name in ["Ali", "Sara"]')

   name  salary department
0   Ali   50000         IT
1  Sara   80000         HR