### How to do Skimming of the data

# What EDA really is (not the buzzword version)

Exploratory Data Analysis (EDA) is the process of understanding reality hidden inside raw data before you touch models, dashboards, or decisions.
Clients don’t pay for algorithms.They pay for clarity, confidence, and correct decisions.
EDA is how you get there.

# The Purpose of EDA (Client-Centric View)

1-To Understand What the Data Actually Represents

Clients often think they know their data.
They usually don’t.

Example:
Column: temperature
Client says: “This is daily temperature”\
EDA reveals:\
Some values are in °C, some in °F
Some are sensor errors (-999, 0)
Some days are missing

👉 Without EDA, your model is garbage in → garbage out.
<br>
EDA answers:\
1.What does each column really mean?\
2.What unit, scale, and range does it live in?\
3.Is this column even usable?

2- To Detect Data Quality Problems\
In real-world projects:
70–80% of effort is data cleaning, Clients rarely mention problems upfront\ 
EDA helps you find:
Missing values,
Duplicates,
Outliers,
Inconsistent categories,
Impossible values

Example (ecological data):\
Species count = -5,
Rainfall = 5000 mm/day,
Population = 0 for an inhabited region,\
These aren’t “small issues.” They change conclusions.

👉 Clients love EDA because it protects them from wrong decisions.

In [4]:
# import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import ydata_profiling as yd
# from skimpy import skim

In [5]:
df_GPS= pd.read_csv('./data/googleplaystore.csv')

In [6]:
df_GPS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [7]:
df_GPS.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,8-Jun-18,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up

In [8]:
df_GPS.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

In [9]:
# Run automatic EDA anlaysis
profile = yd.ProfileReport(df_GPS)
profile.to_file(output_file='./ouputs/04_clean_ydata_kaggle_googleapp.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 13/13 [00:00<00:00, 13.72it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
df_GPS.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
7458,CK FFXIV Companion,FAMILY,4.3,1364,5.2M,"100,000+",Free,0,Everyone,Entertainment,12-Jul-18,4.3.5,2.3 and up
873,MEGOGO - Cinema and TV,ENTERTAINMENT,4.0,175528,Varies with device,"10,000,000+",Free,0,Everyone,Entertainment,3-Aug-18,Varies with device,Varies with device
10359,Le Fe de Jesus,BOOKS_AND_REFERENCE,NaN,3,4.1M,500+,Free,0,Everyone,Books & Reference,17-Dec-15,1,2.3.3 and up
6100,BF-Calc,TOOLS,3.9,428,3.8M,"100,000+",Free,0,Everyone,Tools,31-Mar-15,1.2.5,2.3.3 and up
2012,Racing in Car 2,GAME,4.3,234110,38M,"50,000,000+",Free,0,Everyone,Racing,22-Nov-16,1,2.3.3 and up
2419,Advanced Comprehension Therapy,MEDICAL,NaN,3,62M,100+,Paid,$24.99,Everyone,Medical,5-Oct-17,1.2,4.0.3 and up
10666,PIP-Camera FN Photo Effect,PHOTOGRAPHY,4.6,8,9.0M,"1,000+",Free,0,Everyone,Photography,4-Dec-16,1,2.3 and up
3562,Google Calendar,PRODUCTIVITY,4.2,858230,Varies with device,"500,000,000+",Free,0,Everyone,Productivity,6-Aug-18,Varies with device,Varies with device
5635,DIRECTV,FAMILY,4.1,235486,63M,"10,000,000+",Free,0,Teen,Entertainment,1-Jun-18,5.9.006,4.1 and up
502,Find Real Love — YouLove Premium Dating,DATING,4.5,212626,11M,"10,000,000+",Free,0,Mature 17+,Dating,31-Jul-18,4.17.2,4.1 and up

In [11]:
df_GPS['Size'].unique()
df_GPS['Size'].nunique()

461

In [12]:
df_GPS['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
253k                     1
992k                     1
658k                     1
73k                      1
246k                     1
Name: count, Length: 461, dtype: int64

In [13]:
df_GPS['Installs'].value_counts()

Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             908
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Name: count, dtype: int64

In [14]:
# converting k into M for size column
df_GPS = pd.read_csv('./data/googleplaystore.csv', dtype={'Size': str})

In [15]:
# Ensure Size is string
# Series object ke paas .strip() method nahi hota. .strip() sirf Python string object ke liye hota hai.
df_GPS['Size'] = df_GPS['Size'].astype(str).str.strip()

In [16]:
# Replace 'Varies with device'
df_GPS['Size'] = df_GPS['Size'].replace('Varies with device', np.nan)

In [17]:
# Extract numbers Basically, text me se numeric value extract karna.
size_num = df_GPS['Size'].str.extract(r'([\d.]+)')[0]

# .str.extract() → Pandas string method hai jo regular expression (regex) use karta hai aur string se pattern extract karta hai.
# r'([\d.]+)' → ye regex pattern hai.
# \d → kisi bhi digit ko match karta hai (0–9)
# . → dot . ko match karta hai (decimal numbers ke liye)
# [\d.]+ → ek ya zyada digits ya dots ko match karega
# () → parentheses ka matlab hai capture group, matlab ye wahi part return karega jo parentheses ke andar match hua

# ek line say dono tasks
# size_num = df_GPS['Size'].str.extract(r'([\d.]+)')[0].astype(float)

In [18]:
# Detect units
is_mb = df_GPS['Size'].str.contains('M', na=False)
is_kb = df_GPS['Size'].str.contains('k', na=False)

In [19]:
# Convert to MB
df_GPS['Size'] = np.where(is_mb,size_num.astype(float),np.where(is_kb,size_num.astype(float) / 1024,np.nan))

In [20]:
# import numpy as np
# import pandas as pd

# # Read data
# df_GPS = pd.read_csv('./data/googleplaystore.csv')

# # Clean Size column
# df_GPS['Size'] = (
#     df_GPS['Size']
#     .replace('Varies with device', np.nan)
#     .str.replace('M', '', regex=False)
#     .str.replace('k', '', regex=False)
# )

# # Convert to numeric
# df_GPS['Size'] = pd.to_numeric(df_GPS['Size'], errors='coerce')

# # Convert kB to MB
# df_GPS.loc[df_GPS['Size'] > 100, 'Size'] = df_GPS['Size'] / 1024

In [21]:
df_GPS['Size'].value_counts()

Size
11.000000    198
12.000000    196
14.000000    194
13.000000    191
15.000000    184
            ...
0.539062       1
0.864258       1
0.996094       1
0.568359       1
0.604492       1
Name: count, Length: 459, dtype: int64

In [22]:
df_GPS['Size'].isnull()
df_GPS['Size']

0        19.0
1        14.0
2         8.7
3        25.0
4         2.8
         ...
10836    53.0
10837     3.6
10838     9.5
10839     NaN
10840    19.0
Name: Size, Length: 10841, dtype: float64

In [23]:
# Convert all the numeric column into numeric variable
numeric_cols = ['Reviews', 'Price']

df_GPS[numeric_cols] = df_GPS[numeric_cols].apply(
    pd.to_numeric, errors='coerce')
df_GPS.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size              float64
Installs           object
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [24]:
df_GPS.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0.0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0.0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0.0,Teen,Art & Design,8-Jun-18,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up

In [25]:
# Size,Installs,Review
numeric_cols = ['Reviews', 'Price']

df_GPS[numeric_cols] = df_GPS[numeric_cols].apply(
    pd.to_numeric, errors='coerce'
)

In [26]:
# If column contains symbols (real-world case) e.g "1,000+", "10+", "$4.99"

df_GPS['Installs'] = (
    df_GPS['Installs']
    # .str.replace('$', '', regex=False)
    .str.replace('+', '', regex=False)
    .str.replace(',','',  regex=False)
    .astype(int)
)

In [27]:
# in installs column we remove + sign
df_GPS.head() 
# df_GPS.dtypes

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,8-Jun-18,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up

In [28]:
# If the column is already clean (no text)
# df_GPS['column_name'] = df_GPS['column_name'].astype(int)

# OR
#df_GPS['column_name'] = df_GPS['column_name'].astype(float)

# # converting column from object to numeric 
# pd.to_numeric(..., errors='coerce') sirf already numeric-looking strings ko convert karta hai
# Agar string mein letters (M/k) hain, wo NaN ban jati hain

In [29]:
# Cleaned Data ko CSV file mein save karna (MOST COMMON)
df_GPS.to_csv("./data/googleplaystore_cleaned.csv", index=False)

In [33]:
df_GPS['Size'].value_counts()

Size
11.000000    198
12.000000    196
14.000000    194
13.000000    191
15.000000    184
            ...
0.539062       1
0.864258       1
0.996094       1
0.568359       1
0.604492       1
Name: count, Length: 459, dtype: int64